// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeShape } from "./RangeShape";
import type { SelectorKind } from "./SelectorKind";

/**
 * A text-animator selector. Range fields are percentages (0..100). Wiggly
 * randomises the per-character selection over time.
 */
export type AnimSelector = { kind: SelectorKind, start: number, end: number, offset: number, smoothness: number, easeHigh: number, easeLow: number, shape: RangeShape, wigglesPerSec: number, amount: number, correlation: number, temporalPhase: number, spatialPhase: number, seed: number, };
