// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * The per-character property offsets a text animator applies (scaled by the
 * selector amount). Units: position px, rotation/skew degrees, scale/opacity
 * percent (100 = no change), tracking/blur px, fill overrides the glyph colour.
 */
export type AnimProps = { position: [number, number], scale: number, rotation: number, skew: number, skewAxis: number, opacity: number, tracking: number, blur: number, fill: Rgba | null, 
/**
 * Unicode code-point shift; persisted, not yet applied (needs reshape).
 */
charOffset: number, 
/**
 * Per-character 3D (only applied when the layer's `per_char_3d` is on):
 * X/Y rotation in degrees and Z position in px.
 */
rotationX: number, rotationY: number, positionZ: number, };
