// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";
import type { Track } from "./Track";

/**
 * The per-character property offsets a text animator applies (scaled by the
 * selector amount). Units: position px, rotation/skew degrees, scale/opacity
 * percent (100 = no change), tracking/blur px, fill overrides the glyph colour.
 * Every numeric field is a keyframeable `Track`.
 */
export type AnimProps = { position: [Track, Track], scale: Track, rotation: Track, skew: Track, skewAxis: Track, opacity: Track, tracking: Track, blur: Track, fill: Rgba | null, 
/**
 * Unicode code-point shift; persisted, not yet applied (needs reshape).
 */
charOffset: number, 
/**
 * Per-character 3D (only applied when the layer's `per_char_3d` is on):
 * X/Y rotation in degrees and Z position in px.
 */
rotationX: Track, rotationY: Track, positionZ: Track, };
