// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeShape } from "./RangeShape";
import type { SelectorKind } from "./SelectorKind";
import type { Track } from "./Track";

/**
 * A text-animator selector. Range fields are percentages (0..100). Wiggly
 * randomises the per-character selection over time. Every numeric field is a
 * keyframeable `Track` — animate the selector's `offset` (or start/end) to
 * sweep the selection across the letters over time (the classic AE move).
 */
export type AnimSelector = { kind: SelectorKind, start: Track, end: Track, offset: Track, smoothness: Track, easeHigh: Track, easeLow: Track, shape: RangeShape, wigglesPerSec: Track, amount: Track, correlation: Track, temporalPhase: Track, spatialPhase: Track, seed: number, };
