// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BevelStyle } from "./BevelStyle";

/**
 * Bevel / emboss layer style (stylised: offset highlight + shadow copies).
 */
export type BevelEmboss = { style: BevelStyle, depth: number, size: number, soften: number, angle: number, };
