// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";
import type { Rgba } from "./Rgba";

/**
 * A keyframe on a text layer's fill colour. `easing` shapes the segment that
 * STARTS at this key (mirrors `Keyframe` for scalar tracks). A colour can't ride
 * a scalar `Track` (it's four channels), so text colour gets its own key list.
 */
export type ColorKey = { timeMs: number, color: Rgba, easing: Easing, };
