// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How dragging a `FrameGrid` vertex behaves.
 */
export type ConstrainMode = "freeform" | "rails";
