// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source-pixel crop rectangle applied when drawing an `Image` layer. When set,
 * only this region of the source image is painted (cover-cropping to fill a cell
 * block without stretching); `None` draws the whole image.
 */
export type CropRect = { x: number, y: number, width: number, height: number, };
