// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pins an image to a `Shape3D` so it renders as a decal on the shape's surface.
 * The placement is *within the face's plane*: `(u, v)` is the decal centre in
 * face coordinates (0..1), `scale` its size (fraction of the face / shape size,
 * image aspect preserved), and `rotation` its in-plane spin.
 */
export type Decal = { 
/**
 * Id of the `Shape3D` layer this image is pinned to.
 */
shapeId: number, 
/**
 * Which box face (0=front,1=back,2=left,3=right,4=top,5=bottom). For a
 * cylinder this is ignored — the decal sits tangent to the surface at `u`.
 */
face: number, u: number, v: number, scale: number, rotation: number, };
