// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

/**
 * Pins a layer (image or text) to a `Shape3D` so it renders as a decal on the
 * shape's surface. The placement is keyframeable, so the decal can be animated
 * *across the surface* independently of the shape's own motion: `(u, v)` is the
 * decal centre in surface coordinates (0..1), `scale` its size (image aspect
 * preserved), and `rotation` its in-plane spin (box faces only).
 */
export type Decal = { 
/**
 * Id of the `Shape3D` layer this layer is pinned to.
 */
shapeId: number, 
/**
 * Which box face (0=front,1=back,2=left,3=right,4=top,5=bottom). For a
 * cylinder this is ignored — the decal wraps the surface around `u`.
 */
face: number, u: Track, v: Track, scale: Track, rotation: Track, };
