// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * Drop shadow layer style.
 */
export type DropShadow = { color: Rgba, opacity: number, angle: number, distance: number, size: number, };
