// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

/**
 * A visual effect in a layer's effect stack. Most map to a CSS/canvas filter
 * (applied in order); `Wipe` is a directional gradient mask (the "fade left to
 * right" / reveal). The numeric parameters are keyframeable Tracks so an effect
 * can animate (e.g. a wipe sweeping across).
 */
export type Effect = { "kind": "grayscale", amount: Track, } | { "kind": "brightness", amount: Track, } | { "kind": "contrast", amount: Track, } | { "kind": "saturate", amount: Track, } | { "kind": "blur", radius: Track, } | { "kind": "hue", degrees: Track, } | { "kind": "invert", amount: Track, } | { "kind": "wipe", angle: number, position: Track, softness: Track, invert: boolean, };
