// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a cell's image is fitted into its (possibly warped) cell.
 */
export type FitMode = "cover" | "contain" | "stretch";
