// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable face (style) of a family: a human name plus the weight/italic
 * it maps to. The frontend shows `name` and stores `weight`/`italic`.
 */
export type FontFace = { name: string, weight: number, italic: boolean, };
