// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A font choice: a family NAME. The four built-ins below are always available
 * (embedded, SIL OFL, Persian/Arabic + Latin); any other name is resolved from
 * the system font database. Rendering as outlines means any font explodes into
 * shapes, so no runtime font is needed once shaped.
 */
export type Font = string;
