// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The embedded fonts the user can pick from (all SIL OFL, Persian/Arabic with
 * Latin coverage). Rendering as outlines means any of them explode into shapes.
 */
export type Font = "vazirmatn" | "sahel" | "shabnam" | "gandom";
