// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { FitMode } from "./FitMode";
import type { Track } from "./Track";
import type { Transition } from "./Transition";

/**
 * One image cell of a `FrameGrid` (a lightweight child, not a timeline layer).
 * `src` is an absolute image path (`None` = an empty cell). `effects` is the
 * cell's own effect stack, applied when it renders.
 */
export type FrameCell = { src: string | null, imgW: number, imgH: number, fit: FitMode, 
/**
 * Keyframeable zoom of the image within its cell (1 = fit per `fit`, >1 =
 * zoomed in / cropped, <1 = zoomed out). Scales about the cell centre.
 */
zoom: Track, 
/**
 * Merge spans: how many columns/rows this cell covers (1 = a single slot).
 * A cell with span > 1 is the "master" of a merged block; the slots it
 * covers render nothing (their images are cleared on merge).
 */
colSpan: number, rowSpan: number, effects: Array<Effect>, 
/**
 * Per-cell in/out transitions, played over the grid layer's start/end (the
 * cell's image assembles in / breaks out). Same engine as layer transitions.
 */
transitionIn: Transition | null, transitionOut: Transition | null, };
