// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { GradientStop } from "./GradientStop";

/**
 * Gradient overlay layer style.
 */
export type GradientOverlay = { opacity: number, angle: number, blend: BlendMode, stops: Array<GradientStop>, };
