// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

export type GradientStop = { position: number, color: Rgba, };
