// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

/**
 * One vertex of a `FrameGrid`'s lattice — a keyframeable offset (px) from the
 * vertex's regular grid position, so warps can animate over time.
 */
export type GridVertex = { dx: Track, dy: Track, };
