// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

export type Keyframe = { 
/**
 * Keyframe time in ms. Deserialized leniently (a fractional value from a
 * scrubbed playhead is rounded) so a keyframe minted at a non-integer ms
 * doesn't reject the whole payload — that silently broke keyframing.
 */
timeMs: number, value: number, 
/**
 * Easing applied across the segment that STARTS at this keyframe.
 */
easing: Easing, };
