// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

export type Keyframe = { timeMs: number, value: number, 
/**
 * Easing applied across the segment that STARTS at this keyframe.
 */
easing: Easing, };
