// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { LetterAnimation } from "./LetterAnimation";
import type { Rgba } from "./Rgba";

/**
 * What a layer actually draws. Internally tagged so the TS side is a clean
 * discriminated union on `kind`.
 */
export type LayerKind = { "kind": "image", src: string, width: number, height: number, } | { "kind": "text", content: string, size: number, color: Rgba, anim: LetterAnimation | null, } | { "kind": "colorpatch", color: Rgba, blend: BlendMode, width: number, height: number, };
