// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decal } from "./Decal";
import type { Effect } from "./Effect";
import type { LayerKind } from "./LayerKind";
import type { Transform } from "./Transform";

/**
 * One item on the timeline.
 */
export type Layer = { id: number, name: string, 
/**
 * Time range during which the layer is visible (comp time, ms).
 */
startMs: number, endMs: number, kind: LayerKind, 
/**
 * Animatable transform. Keyframe times are in comp time (absolute).
 */
transform: Transform, 
/**
 * Manually toggled off in the layer list (independent of the time range).
 */
hidden: boolean, 
/**
 * When set, this layer is pinned to a `Shape3D` and renders as a decal on
 * its surface instead of flat. Honoured for image and text layers.
 */
attach: Decal | null, 
/**
 * A stack of visual effects applied in order when the layer renders
 * (currently honoured for flat image layers). Keyframeable.
 */
effects: Array<Effect>, };
