// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerKind } from "./LayerKind";
import type { Transform } from "./Transform";

/**
 * One item on the timeline.
 */
export type Layer = { id: number, name: string, 
/**
 * Time range during which the layer is visible (comp time, ms).
 */
startMs: number, endMs: number, kind: LayerKind, 
/**
 * Animatable transform. Keyframe times are in comp time (absolute).
 */
transform: Transform, };
