// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { ColorKey } from "./ColorKey";
import type { ConstrainMode } from "./ConstrainMode";
import type { CropRect } from "./CropRect";
import type { Font } from "./Font";
import type { FrameCell } from "./FrameCell";
import type { GridVertex } from "./GridVertex";
import type { Layer } from "./Layer";
import type { LetterAnimation } from "./LetterAnimation";
import type { LetterOverride } from "./LetterOverride";
import type { LinkedEffectGroup } from "./LinkedEffectGroup";
import type { Rgba } from "./Rgba";
import type { Shape2DStyle } from "./Shape2DStyle";
import type { SurfaceShape } from "./SurfaceShape";
import type { TextAlign } from "./TextAlign";
import type { TextAnimator } from "./TextAnimator";
import type { TextLayerStyles } from "./TextLayerStyles";
import type { TextStyle } from "./TextStyle";
import type { Track } from "./Track";

/**
 * What a layer actually draws. Internally tagged so the TS side is a clean
 * discriminated union on `kind`.
 */
export type LayerKind = { "kind": "image", src: string, width: number, height: number, crop: CropRect | null, } | { "kind": "shape3d", shape: SurfaceShape, 
/**
 * Box/cylinder dimensions (px). Keyframeable — animate the size over the
 * clip. Bare numbers in older projects deserialize as constant tracks.
 */
width: Track, height: Track, 
/**
 * Box depth (px). Ignored for cylinders. Keyframeable.
 */
depth: Track, rotation_x: Track, rotation_y: Track, rotation_z: Track, 
/**
 * 0 = orthographic, 1 = full perspective foreshortening. Keyframeable.
 */
perspective: Track, 
/**
 * Camera distance (px-ish). Larger = flatter perspective. Keyframeable.
 */
focal_length: Track, 
/**
 * Cylinder: degrees of circumference shown (0..360). Ignored for boxes.
 * Keyframeable.
 */
coverage: Track, 
/**
 * Cylinder: radius (px). Ignored for boxes. Keyframeable.
 */
radius: Track, } | { "kind": "text", 
/**
 * The text; may contain `'\n'` line breaks for multi-line paragraphs.
 */
content: string, 
/**
 * Font size in px (the letter "height").
 */
size: number, 
/**
 * Horizontal alignment of the lines in a multi-line run.
 */
align: TextAlign, color: Rgba, 
/**
 * Keyframeable fill colour. When non-empty this overrides `color` and is
 * interpolated at the current time, so the text colour animates over the
 * clip. Empty = the static `color` fill (back-compatible).
 */
colorKeys: Array<ColorKey>, font: Font, 
/**
 * Font weight (100..900, CSS scale; 400 = Regular, 700 = Bold). Used to
 * pick the matching face from the family when shaping.
 */
weight: number, 
/**
 * Select the italic/oblique face of the family when available.
 */
italic: boolean, anim: LetterAnimation | null, parts: Array<LetterOverride>, 
/**
 * Keyframeable 0..1: how much of `parts` is applied. 0 = composed,
 * 1 = fully decomposed. Keyframe it to animate the decompose effect.
 */
decompose: Track, 
/**
 * Optional typographic + fill/stroke style (After Effects-style). `None`
 * = the plain single-colour fill from `color` (back-compatible).
 */
style: TextStyle | null, 
/**
 * After Effects-style per-character animators (Range/Wiggly selectors
 * driving position/scale/rotation/opacity/tracking/skew/blur/colour).
 */
animators: Array<TextAnimator>, 
/**
 * Whole-layer non-destructive layer styles (shadow/glow/bevel/gradient).
 */
layerStyles: TextLayerStyles | null, 
/**
 * Enable per-character 3D (animator rotationX/Y + positionZ apply, and
 * the base per-character rotation below).
 */
perChar3d: boolean, 
/**
 * Base per-character 3D rotation applied to EVERY glyph about its own
 * centre (degrees). `per_char_spread` adds `index * spread` to the Y
 * rotation so the characters fan out in a 3D wave.
 */
perCharRx: number, perCharRy: number, perCharSpread: number, } | { "kind": "colorpatch", color: Rgba, blend: BlendMode, width: number, height: number, } | { "kind": "framegrid", rows: number, cols: number, 
/**
 * Un-warped cell size in layer-local px. Grid is centred on the origin.
 */
cell_w: number, cell_h: number, 
/**
 * Per-vertex warp offset (row-major, (rows+1)*(cols+1)). Empty = regular.
 */
vertices: Array<GridVertex>, constrain: ConstrainMode, 
/**
 * One per cell (row-major, rows*cols).
 */
cells: Array<FrameCell>, 
/**
 * Shared effect stacks applied across several cells at once (the "sync"
 * feature). A member cell renders its local effects then each linked
 * group it belongs to.
 */
linked: Array<LinkedEffectGroup>, 
/**
 * Grid line thickness in layer-local px (0 = no lines drawn). Scaled by
 * the layer transform like the rest of the mesh.
 */
line_width: number, 
/**
 * Base grid line colour. Overridden by `line_color_keys` when non-empty
 * (so the line colour can be keyframed over the clip).
 */
line_color: Rgba, 
/**
 * Keyframeable grid line colour. Empty = the static `line_color`.
 */
lineColorKeys: Array<ColorKey>, 
/**
 * Optional shared BACKGROUND image spanning the whole grid. When set,
 * every cell reveals its aligned slice of this one image (a mask over a
 * single photo) instead of its own `src`, and each cell's effect stack
 * applies to that slice. `None` = per-cell images (the classic mode).
 */
background: string | null, } | { "kind": "video", src: string, width: number, height: number, durationMs: number, 
/**
 * Source in-point: the media time (ms) shown at the layer's start.
 * Trimming the head or splitting the clip advances this, so each piece
 * plays its own portion of the source instead of restarting from 0.
 */
inMs: number, } | { "kind": "audio", src: string, durationMs: number, } | { "kind": "group", children: Array<Layer>, } | { "kind": "adjustment", } | { "kind": "shape2d", style: Shape2DStyle, };
