// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LetterPreset } from "./LetterPreset";

/**
 * Per-letter animation for `Text` layers, driven by a named preset. Each glyph
 * runs the preset over `duration_ms`, offset from its neighbour by `stagger_ms`
 * — so the letters animate in sequence. The actual per-letter math lives in the
 * evaluator (single source of truth).
 */
export type LetterAnimation = { preset: LetterPreset, 
/**
 * When the first letter starts (comp ms).
 */
startMs: number, 
/**
 * How long a single letter takes to settle (ms).
 */
durationMs: number, 
/**
 * Delay added per letter index (ms).
 */
staggerMs: number, };
