// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One glyph's offset from its resting shaped position at a given time.
 */
export type LetterTransform = { dx: number, dy: number, scale: number, opacity: number, rotation: number, };
