// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The predefined per-letter effects the user can pick from.
 */
export type LetterPreset = "fadeIn" | "scalePop" | "riseUp" | "scatterIn" | "typewriter";
