// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * One glyph's offset from its resting shaped position at a given time.
 */
export type LetterTransform = { dx: number, dy: number, scale: number, opacity: number, rotation: number, 
/**
 * Skew (shear) in degrees, and the axis the skew is measured along (degrees).
 */
skew: number, skewAxis: number, 
/**
 * Extra letter-spacing added for this glyph (px, cumulative along the run).
 */
tracking: number, 
/**
 * Per-glyph Gaussian blur radius (px).
 */
blur: number, 
/**
 * Per-glyph fill override (from a colour animator); `None` = the layer fill.
 */
fill: Rgba | null, 
/**
 * Per-character 3D (only when the layer enables it): X/Y rotation (degrees)
 * and Z position (px).
 */
rx: number, ry: number, dz: number, };
