// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorKey } from "./ColorKey";
import type { Track } from "./Track";

/**
 * A manual per-glyph transform for "decompose" mode: move / rotate / scale one
 * letter by hand. Added on top of (independent of) any preset animation.
 *
 * Each channel is its own keyframe track, so an individual letter can be
 * animated over time — drag it at one playhead position, drag it at another,
 * and it tweens between — exactly like the whole layer's transform keyframes.
 */
export type LetterOverride = { dx: Track, dy: Track, rotation: Track, scale: Track, 
/**
 * Keyframeable per-letter fill colour. Empty = the letter uses the layer's
 * colour; non-empty overrides it (and animates, like the layer colour).
 */
colorKeys: Array<ColorKey>, };
