// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A manual per-glyph transform for "decompose" mode: move / rotate / scale one
 * letter by hand. Added on top of (independent of) any preset animation.
 */
export type LetterOverride = { dx: number, dy: number, rotation: number, scale: number, };
