// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";

/**
 * A shared effect stack applied to several `FrameGrid` cells at once. Editing it
 * updates every member; "unlinking" a cell copies these effects into that cell's
 * own stack so it can diverge.
 */
export type LinkedEffectGroup = { id: number, effects: Array<Effect>, 
/**
 * Cell indices (row-major) this group applies to.
 */
members: Array<number>, };
