// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layer } from "./Layer";

/**
 * A complete animation project. This is what gets serialised to `.ron` on save
 * and handed to the export pipeline.
 */
export type Project = { width: number, height: number, fps: number, durationMs: number, 
/**
 * Drawn back-to-front: index 0 is the bottom layer.
 */
layers: Array<Layer>, };
