// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layer } from "./Layer";

/**
 * A complete animation project. This is what gets serialised to `.ron` on save
 * and handed to the export pipeline.
 */
export type Project = { width: number, height: number, fps: number, durationMs: number, 
/**
 * Drawn back-to-front: index 0 is the bottom layer.
 */
layers: Array<Layer>, 
/**
 * The media bin: imported image/video/audio file paths staged for this
 * project (not necessarily placed on the timeline). Saved with the project
 * so reopening a file restores its bin; a new project starts empty.
 */
media: Array<string>, };
