// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A projected quad corner: homogeneous screen position + texture coordinate.
 */
export type QuadVertex = { hx: number, hy: number, hw: number, u: number, v: number, };
