// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Range-selector falloff shape.
 */
export type RangeShape = "square" | "rampUp" | "rampDown" | "triangle" | "round" | "smooth";
