// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One effect with its parameters resolved at a point in time (camelCase field
 * names map straight onto the frontend renderer).
 */
export type ResolvedEffect = { "kind": "grayscale", amount: number, } | { "kind": "brightness", amount: number, } | { "kind": "contrast", amount: number, } | { "kind": "saturate", amount: number, } | { "kind": "blur", radius: number, } | { "kind": "hue", degrees: number, } | { "kind": "invert", amount: number, } | { "kind": "wipe", angle: number, position: number, softness: number, invert: boolean, };
