// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceQuad } from "./SurfaceQuad";

/**
 * A pinned layer projected onto the shape: paint-ready quads (empty if the
 * decal faces away from the camera), plus the placement sampled at this time
 * (for the inspector's sliders).
 */
export type ResolvedSurface = { quads: Array<SurfaceQuad>, u: number, v: number, scale: number, rotation: number, };
