// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedFrameCell } from "./ResolvedFrameCell";
import type { Vec2 } from "./Vec2";

/**
 * A `FrameGrid` resolved at one instant: the (possibly warped) vertex lattice
 * plus one paint-ready cell per grid cell. Geometry is in LAYER-LOCAL px
 * (centred on the origin); the frontend draws it under the layer's transform.
 */
export type ResolvedFrameGrid = { rows: number, cols: number, 
/**
 * The lattice in layer-local px (row-major, (rows+1)*(cols+1)) — for the
 * mesh overlay + editing handles.
 */
vertices: Array<Vec2>, cells: Array<ResolvedFrameCell>, };
