// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * One effect with its parameters resolved at a point in time (camelCase field
 * names map straight onto the frontend renderer).
 */
export type ResolvedEffect = { "kind": "grayscale", amount: number, } | { "kind": "brightness", amount: number, } | { "kind": "contrast", amount: number, } | { "kind": "saturate", amount: number, } | { "kind": "blur", radius: number, } | { "kind": "hue", degrees: number, } | { "kind": "invert", amount: number, } | { "kind": "wipe", angle: number, position: number, softness: number, invert: boolean, } | { "kind": "shinyclouds", time: number, intensity: number, scale: number, speed: number, complexity: number, contrast: number, brightness: number, opacity: number, tint: Rgba, blend: number, } | { "kind": "gpuoverlay", effect: number, time: number, intensity: number, scale: number, speed: number, detail: number, softness: number, extra: number, opacity: number, tint: Rgba, tint2: Rgba, posX: number, posY: number, blend: number, };
