// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitMode } from "./FitMode";
import type { ResolvedEffect } from "./ResolvedEffect";
import type { ResolvedTransition } from "./ResolvedTransition";
import type { SurfaceQuad } from "./SurfaceQuad";

/**
 * One resolved grid cell: a flat local-space quad (hw = 1), its image source +
 * natural size, fit mode, and its effect stack sampled at this time.
 */
export type ResolvedFrameCell = { quad: SurfaceQuad, src: string | null, imgW: number, imgH: number, fit: FitMode, 
/**
 * Zoom sampled at this time (for the inspector's slider readout).
 */
zoom: number, 
/**
 * Grid position + merge spans (so the frontend can map a cell back to its
 * lattice vertices for live-warp, and know its size).
 */
row: number, col: number, rowSpan: number, colSpan: number, 
/**
 * True when this slot is absorbed into another cell's merged block — the
 * frontend skips it (no draw, no gridline, not clickable).
 */
covered: boolean, effects: Array<ResolvedEffect>, 
/**
 * The cell's active in/out transition at this time (played over the grid
 * layer's start/end). `None` outside any window.
 */
transition: ResolvedTransition | null, };
