// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedEffect } from "./ResolvedEffect";

/**
 * A linked effect group resolved at this time (its shared stack + members).
 */
export type ResolvedLinkedEffect = { id: number, effects: Array<ResolvedEffect>, members: Array<number>, };
