// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKind } from "./TransitionKind";

/**
 * A layer's in/out transition resolved at a point in time.
 */
export type ResolvedTransition = { kind: TransitionKind, 
/**
 * 0 = fully transitioned-out, 1 = fully present (eased).
 */
factor: number, direction: number, };
