// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedLayer } from "./ResolvedLayer";

/**
 * A nested composition resolved at one instant: its child layers, each already
 * resolved (recursively) at the same comp time.
 */
export type ResolvedGroup = { children: Array<ResolvedLayer>, };
