// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LetterTransform } from "./LetterTransform";
import type { ResolvedEffect } from "./ResolvedEffect";
import type { ResolvedFrameGrid } from "./ResolvedFrameGrid";
import type { ResolvedGroup } from "./ResolvedGroup";
import type { ResolvedShape2D } from "./ResolvedShape2D";
import type { ResolvedShapeFrame } from "./ResolvedShapeFrame";
import type { ResolvedSurface } from "./ResolvedSurface";
import type { ResolvedTransition } from "./ResolvedTransition";
import type { Rgba } from "./Rgba";

/**
 * A layer's transform fully resolved at one instant in time. Field names are
 * camelCase so they map straight onto Konva node props on the frontend.
 */
export type ResolvedLayer = { id: number, 
/**
 * Whether the layer is within its [startMs, endMs] range at this time.
 */
visible: boolean, x: number, y: number, scaleX: number, scaleY: number, rotation: number, opacity: number, 
/**
 * Anchor / pivot in normalized layer coords (0.5,0.5 = centre). The renderer
 * places the layer's position at this point and pivots scale/rotation on it.
 */
anchorX: number, anchorY: number, 
/**
 * Per-letter offsets for animated `Text` layers (one per shaped glyph,
 * in glyph order). Empty for everything else.
 */
letters: Array<LetterTransform>, 
/**
 * Text fill colour sampled at this time (interpolated from `color_keys`, or
 * the static fill when the layer isn't keyed). `None` for non-text layers.
 */
color: Rgba | null, 
/**
 * Paint-ready decal quads when this is an image pinned to a `Shape3D`.
 * `None` = render the image flat.
 */
surface: ResolvedSurface | null, 
/**
 * Visible-face polygons when this is a `Shape3D` layer (for the selection
 * wireframe + hit area). `None` for everything else.
 */
shape: ResolvedShapeFrame | null, 
/**
 * The layer's effect stack with every parameter sampled at this time, in
 * apply order. Empty when the layer has no effects.
 */
effects: Array<ResolvedEffect>, 
/**
 * Active in/out transition at this time (factor 0 = fully transitioned /
 * hidden, 1 = fully present). `None` outside any transition window.
 */
transition: ResolvedTransition | null, 
/**
 * Resolved multi-frame grid (cells + warped lattice) when this is a
 * `FrameGrid` layer. `None` for everything else.
 */
frameGrid: ResolvedFrameGrid | null, 
/**
 * Resolved child layers when this is a `Group` (precomp) — the frontend
 * renders them nested under this layer's transform. `None` otherwise.
 */
group: ResolvedGroup | null, 
/**
 * Resolved 2D vector shape (fill/border/glow/shadow, every colour + knob
 * sampled at this time) when this is a `Shape2D` layer. `None` otherwise.
 */
shape2d: ResolvedShape2D | null, };
