// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";
import type { VectorShape } from "./VectorShape";

/**
 * A `Shape2D` resolved at one instant: the geometry plus every paint property
 * sampled at this time (colours interpolated from their key lists, numeric
 * knobs from their tracks). camelCase → Konva-friendly on the frontend.
 */
export type ResolvedShape2D = { shape: VectorShape, width: number, height: number, sides: number, cornerRadius: number, 
/**
 * false = hollow (outline only).
 */
filled: boolean, fill: Rgba, borderWidth: number, borderColor: Rgba, glowColor: Rgba, glowSize: number, glowOpacity: number, shadowColor: Rgba, shadowBlur: number, shadowOffsetX: number, shadowOffsetY: number, shadowOpacity: number, };
