// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceQuad } from "./SurfaceQuad";

/**
 * A pinned image projected onto the shape: paint-ready quads (empty if the
 * decal faces away from the camera).
 */
export type ResolvedSurface = { quads: Array<SurfaceQuad>, };
