// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LetterTransform } from "./LetterTransform";
import type { ResolvedEffect } from "./ResolvedEffect";
import type { ResolvedShapeFrame } from "./ResolvedShapeFrame";
import type { ResolvedSurface } from "./ResolvedSurface";

/**
 * A layer's transform fully resolved at one instant in time. Field names are
 * camelCase so they map straight onto Konva node props on the frontend.
 */
export type ResolvedLayer = { id: number, 
/**
 * Whether the layer is within its [startMs, endMs] range at this time.
 */
visible: boolean, x: number, y: number, scaleX: number, scaleY: number, rotation: number, opacity: number, 
/**
 * Per-letter offsets for animated `Text` layers (one per shaped glyph,
 * in glyph order). Empty for everything else.
 */
letters: Array<LetterTransform>, 
/**
 * Paint-ready decal quads when this is an image pinned to a `Shape3D`.
 * `None` = render the image flat.
 */
surface: ResolvedSurface | null, 
/**
 * Visible-face polygons when this is a `Shape3D` layer (for the selection
 * wireframe + hit area). `None` for everything else.
 */
shape: ResolvedShapeFrame | null, 
/**
 * The layer's effect stack with every parameter sampled at this time, in
 * apply order. Empty when the layer has no effects.
 */
effects: Array<ResolvedEffect>, };
