// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LetterTransform } from "./LetterTransform";

/**
 * A layer's transform fully resolved at one instant in time. Field names are
 * camelCase so they map straight onto Konva node props on the frontend.
 */
export type ResolvedLayer = { id: number, 
/**
 * Whether the layer is within its [startMs, endMs] range at this time.
 */
visible: boolean, x: number, y: number, scaleX: number, scaleY: number, rotation: number, opacity: number, 
/**
 * Per-letter offsets for animated `Text` layers (one per shaped glyph,
 * in glyph order). Empty for everything else.
 */
letters: Array<LetterTransform>, };
