// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

/**
 * The visible faces of a `Shape3D`, projected to 2D. Each face is a closed
 * polygon (4 points for a box face). Used for the wireframe + hit area; the
 * rotation angles feed the inspector sliders.
 */
export type ResolvedShapeFrame = { faces: Array<Array<Vec2>>, rotationX: number, rotationY: number, rotationZ: number, };
