// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKind } from "./TransitionKind";

/**
 * A layer's in/out transition resolved at a point in time.
 */
export type ResolvedTransition = { kind: TransitionKind, 
/**
 * 0 = fully transitioned-out, 1 = fully present (eased).
 */
factor: number, direction: number, 
/**
 * Frontend transition-engine id to render, if the transition uses one.
 */
engine: string | null, 
/**
 * Engine transition variables (JSON object string), passed to the renderer.
 */
params: string | null, };
