// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selector type for a text animator.
 */
export type SelectorKind = "range" | "wiggly" | "expression";
