// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapedGlyph } from "./ShapedGlyph";

export type ShapedText = { glyphs: Array<ShapedGlyph>, 
/**
 * Total advance width of the run (px).
 */
width: number, 
/**
 * Scaled ascender / descender (px, both positive).
 */
ascender: number, descender: number, };
