// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorKey } from "./ColorKey";
import type { Rgba } from "./Rgba";
import type { Track } from "./Track";
import type { VectorShape } from "./VectorShape";

/**
 * The paint style of a `Shape2D` layer. Every colour is keyframeable via its
 * `*_keys` list (empty = the static base colour, mirroring text colour); every
 * numeric knob is a keyframeable `Track`. Fields default to sensible values so
 * older projects and the frontend builder stay in sync.
 */
export type Shape2DStyle = { shape: VectorShape, 
/**
 * Base bounding-box size in comp px (the layer transform scales/rotates on
 * top). Keyframeable — animate the shape's own width/height. Bare numbers in
 * older projects deserialize as constant tracks.
 */
width: Track, height: Track, 
/**
 * Regular-polygon side count (>= 3, rounded when sampled). Ignored for
 * rectangle/circle. Keyframeable so the polygon can morph side counts.
 */
sides: Track, 
/**
 * Rectangle corner radius (px). Ignored for circle/polygon.
 */
cornerRadius: Track, 
/**
 * Arrow curvature (px): perpendicular offset of the shaft's midpoint, so the
 * arrow bows into an arc. 0 = straight. Keyframeable. Ignored by other shapes.
 */
bend: Track, 
/**
 * false = hollow (outline only, no fill) — the border/glow still draw.
 */
filled: boolean, fill: Rgba, fillKeys: Array<ColorKey>, borderWidth: Track, borderColor: Rgba, borderColorKeys: Array<ColorKey>, glowColor: Rgba, glowColorKeys: Array<ColorKey>, glowSize: Track, glowOpacity: Track, 
/**
 * Glow strength multiplier: how many blurred copies stack (1 = the default
 * halo, higher = brighter/denser, lower = fainter). Keyframeable.
 */
glowIntensity: Track, shadowColor: Rgba, shadowColorKeys: Array<ColorKey>, shadowBlur: Track, shadowOffsetX: Track, shadowOffsetY: Track, shadowOpacity: Track, };
