// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorKey } from "./ColorKey";
import type { Rgba } from "./Rgba";
import type { Track } from "./Track";
import type { VectorShape } from "./VectorShape";

/**
 * The paint style of a `Shape2D` layer. Every colour is keyframeable via its
 * `*_keys` list (empty = the static base colour, mirroring text colour); every
 * numeric knob is a keyframeable `Track`. Fields default to sensible values so
 * older projects and the frontend builder stay in sync.
 */
export type Shape2DStyle = { shape: VectorShape, 
/**
 * Base bounding-box size in comp px (the layer transform scales/rotates on
 * top). Adjustable with the width/height sliders.
 */
width: number, height: number, 
/**
 * Regular-polygon side count (>= 3). Ignored for rectangle/circle.
 */
sides: number, 
/**
 * Rectangle corner radius (px). Ignored for circle/polygon.
 */
cornerRadius: Track, 
/**
 * false = hollow (outline only, no fill) — the border/glow still draw.
 */
filled: boolean, fill: Rgba, fillKeys: Array<ColorKey>, borderWidth: Track, borderColor: Rgba, borderColorKeys: Array<ColorKey>, glowColor: Rgba, glowColorKeys: Array<ColorKey>, glowSize: Track, glowOpacity: Track, shadowColor: Rgba, shadowColorKeys: Array<ColorKey>, shadowBlur: Track, shadowOffsetX: Track, shadowOffsetY: Track, shadowOpacity: Track, };
