// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShapedGlyph = { 
/**
 * SVG path data in pixel space, origin at the glyph's pen point (baseline).
 */
d: string, 
/**
 * Pen x of this glyph within the run (px).
 */
x: number, 
/**
 * Horizontal advance (px).
 */
advance: number, 
/**
 * Glyph bounding-box centre in local px (for centred scale/rotate).
 */
cx: number, cy: number, 
/**
 * Source byte cluster — maps a glyph back to the character it came from.
 */
cluster: number, };
