// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapedGlyph } from "./ShapedGlyph";

export type ShapedText = { glyphs: Array<ShapedGlyph>, 
/**
 * Total advance width of the run (px).
 */
width: number, 
/**
 * Scaled ascender / descender (px, both positive) — of a single line.
 */
ascender: number, descender: number, 
/**
 * Baseline-to-baseline distance between lines (px).
 */
lineHeight: number, 
/**
 * Number of lines in the run (>= 1).
 */
lines: number, 
/**
 * Synthetic-bold stroke width (px) to add when the family has no real face
 * heavier than the chosen one. 0 = the outlines are already the right weight
 * (a real Bold/Medium face was found), so the renderer just fills them.
 */
embolden: number, };
