// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a text stroke sits relative to the glyph outline.
 */
export type StrokePosition = "inside" | "center" | "outside";
