// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";

/**
 * One fill layer in a text style (stacked bottom→top).
 */
export type TextFill = { color: Rgba, 
/**
 * Fill opacity, 0..100 (percent).
 */
opacity: number, };
