// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BevelEmboss } from "./BevelEmboss";
import type { DropShadow } from "./DropShadow";
import type { GradientOverlay } from "./GradientOverlay";
import type { TextGlow } from "./TextGlow";

/**
 * The full set of non-destructive layer styles for a text layer.
 */
export type TextLayerStyles = { dropShadow: DropShadow | null, outerGlow: TextGlow | null, innerGlow: TextGlow | null, bevel: BevelEmboss | null, gradient: GradientOverlay | null, };
