// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Horizontal alignment of a multi-line text run: each line is offset within the
 * widest line's box.
 */
export type TextAlign = "left" | "center" | "right" | "justify";
