// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgba } from "./Rgba";
import type { StrokePosition } from "./StrokePosition";

/**
 * One stroke layer in a text style (stacked bottom→top).
 */
export type TextStroke = { color: Rgba, 
/**
 * Stroke opacity, 0..100 (percent).
 */
opacity: number, 
/**
 * Stroke width in px.
 */
width: number, position: StrokePosition, };
