// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimProps } from "./AnimProps";
import type { AnimSelector } from "./AnimSelector";

/**
 * One After Effects-style text animator: a selector + the properties it drives.
 */
export type TextAnimator = { selector: AnimSelector, props: AnimProps, };
