// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { Rgba } from "./Rgba";

/**
 * Inner or outer glow layer style.
 */
export type TextGlow = { color: Rgba, opacity: number, size: number, range: number, mode: BlendMode, };
