// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextFill } from "./TextFill";
import type { TextStroke } from "./TextStroke";

/**
 * After Effects-style typographic + paint style for a text layer. All fields
 * default to "no change", so an empty style renders like the plain `color` fill.
 *
 * Wired to the renderer today: `fills`, `strokes`, `fill_over_stroke`,
 * `tracking`, `baseline_shift`. Persisted but not yet applied (need font /
 * multi-line infrastructure — a later stage): `font_family`, `fallback_stack`,
 * `font_style`, `variable_axes`, `leading`.
 */
export type TextStyle = { fills: Array<TextFill>, strokes: Array<TextStroke>, 
/**
 * true = fill drawn over stroke; false (default) = stroke over fill.
 */
fillOverStroke: boolean, 
/**
 * Letter-spacing added between glyphs, px (negative = tighter).
 */
tracking: number, 
/**
 * Line spacing, px. 0 = auto (single-line today). Reserved for multi-line.
 */
leading: number, 
/**
 * Baseline offset for the whole block, px (positive = up).
 */
baselineShift: number, fontFamily: string | null, fallbackStack: Array<string>, fontStyle: string | null, variableAxes: { [key in string]: number }, };
