// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keyframe } from "./Keyframe";

/**
 * A single animatable property: a list of keyframes plus the value to use when
 * the track is empty.
 */
export type Track = { keys: Array<Keyframe>, default: number, };
