// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial transform edit from the canvas. Only the properties the user
 * actually changed are `Some`; the rest are left untouched.
 */
export type TransformEdit = { x?: number, y?: number, scaleX?: number, scaleY?: number, rotation?: number, opacity?: number, };
