// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionKind } from "./TransitionKind";

/**
 * A per-layer in/out transition. Because layers composite back-to-front, a top
 * layer transitioning in over an overlap with the layer beneath reads as a
 * cross-transition. `direction` (0=left,1=right,2=up,3=down) is used by Slide
 * and Wipe; ignored by Dissolve.
 */
export type Transition = { kind: TransitionKind, durMs: number, direction: number, };
