// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

/**
 * Per-property keyframe tracks. `x`/`y` are the layer's CENTRE in comp pixels;
 * scaling and rotation happen about that centre.
 */
export type Transform = { x: Track, y: Track, scaleX: Track, scaleY: Track, 
/**
 * Degrees, clockwise (matches Konva).
 */
rotation: Track, 
/**
 * 0.0 .. 1.0
 */
opacity: Track, };
