// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A screen-space point (comp px for decals, local px for shape frames).
 */
export type Vec2 = { x: number, y: number, };
