// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 2D vector primitive a `Shape2D` layer draws.
 */
export type VectorShape = "rectangle" | "circle" | "polygon";
